Fix global_functions.c not including "platform.h".
For H7 this results in warnings for `UNUSED` macro re-defined.

Remove unused timer.h dependency from cli.c

Remove unused timer.h dependency from config.c

Fix broken settings `condition`.

Generated code produces:
```
```

and the resulting error is:

```
Output: ./obj/main/SPRACINGH7EXTREME/tmp/test.cpp:112:16: warning: extra
tokens at end of #ifdef directive
  112 | #ifdef USE_NAV && USE_AUTOTUNE_FIXED_WING
      |                ^~
```

Solution appears to be to just use the second part of the condition.

Fix settings code generation error.

Generated code was missing semicolon.

Error was:
```
./obj/main/SOMETARGET/tmp/test.cpp:53:13: error: expected ';' at end of
member declaration
   53 | int64_t v = V
      |             ^
      |              ;
```

targets.mk fixes for H7

Fix incorrect path and comments in H7 .mk file.

Disable compilation of code that's not ported yet or where compilation
would fail.

Fix missing inclusion of `platform.h` from more files.

Fix missing `#pragma once` in debug.h

Consolidate memory initialisation code for all MCUs.

Enable USE_ITCM_RAM on H7.

Relocate and fix the memory selection/noinline macros.

Fix compilation of usbd_cdc_interface for H7.

Add FLASH_PAGE_SIZE for H7

Add H750 compilation support to STM32H7.mk.

* Note also allows target.mk files to override the linker script, this
is useful for development on H750 boards which actually have 1MB of
flash, but only 128k manufacturer supported...

e.g. in target.mk do this (with suitable linker script, of course)

DEFAULT_LD_SCRIPT=$(LINKER_DIR)/stm32_flash_h750_1m.ld

Add H743 startup source.

Add H7 MCU startup code.

Add basic platform.h support for H7.

Add H7 hal config.

Add H7 compilation support to io.h

Fix compiler warning 'missing initializer`.

Avoid duplicate `FLASH_SIZE` when including H7 hal library.

H7 libs define `FLASH_SIZE`.  This uses `TARGET_FLASH_SIZE` instead, as
per BF.

Fix H7 exti compilation.

Fix H7 dma.h compilation.

This needs further work.

Port some H7 USB code.

Temporarily duplicate F7 MSC code for H7.

* Untested.

Add stub drivers/system32h7xx.c

Allow firmware to be compiled when USE_ADC is not defined.

Don't expose SPI/I2C macros when SPI/I2C is not enabled.

Add support for CONFIG_IN_RAM.

* This is useful when porting new new MCUs.
* See https://github.com/betaflight/betaflight/pull/8376
* Pre-requisite to supporting config in external flash and on SD card.

Add H7 support to IO_EXTI_Line.

Allow compilation of rcc.c on H7.

Note: Full RCC support not ported yet.

Allow beeper code to be compiled while timer code has not been ported.

Gate some timer code with `USE_TIMER` to allow compilation when timer
support has not been implemented.

Fix compilation of pwm source files when timer code is not ported to new
MCU.

Gate more timer code with `USE_TIMER`.

Gate more code with `USE_PWM_OUTPUT`

Allow compilation of serial_usb_vcp.c on H7.

Import H7 memprot from BF

H7 USB compilation fixes.

Add H750 linker script.

* CONFIG_IN_FLASH cannot be used with this as there is only one flash
sector - Use a different config storage system.